image: r-base
before_script:
  - R CMD INSTALL -l ../ SIAMCAT
  - cd Rscript_flavor
  - wget http://congo.embl.de/downloads/siamcat_test_data.tar.gz 
  - tar -zxf siamcat_test_data.tar.gz && rm siamcat_test_data.tar.gz

test:
  stage: test
  script: ./execute.sh

after_script:
  - rm -r *.tsv
  - echo "cleaned up"
