image: siamcat/test-env
stages:
  - build
  - preprocess_data
  - train_model
  - make_predictions
  - evaluate_interpret

build:
  stage: build
  script:
  - R CMD build ./ --no-build-vignettes
  - R CMD INSTALL SIAMCAT_1.0.1.tar.gz
  - mv SIAMCAT_* ./Rscript_flavor
  - cd Rscript_flavor
  - wget http://congo.embl.de/downloads/siamcat_test_data.tar.gz
  - tar -zxf siamcat_test_data.tar.gz && rm siamcat_test_data.tar.gz
  artifacts:
    paths:
      - Rscript_flavor/*
    expire_in: 30 min

preprocess_data:
  stage: preprocess_data
  before_script:
    - cd Rscript_flavor
    - R CMD INSTALL SIAMCAT_1.0.1.tar.gz
  script:
    - Rscript 01_validate_data.r --metadata_in num_metadata_cancer-vs-healthy_study-pop-I_N141_tax_profile_mocat_bn_genus.tsv --metadata_out valMetaData.tsv --label_in label_cancer-vs-healthy_study-pop-I_N141_tax_profile_mocat_bn_genus.tsv --label_out valLabel.tsv --feat_in feat_cancer-vs-healthy_study-pop-I_N141_tax_profile_mocat_bn_genus.tsv --feat_out valFeat.tsv
    - Rscript 02_select_samples.r --metadata_in valMetaData.tsv --metadata_out valMetaData_sel.tsv --label_in valLabel.tsv --label_out valLabel_sel.tsv --feat_in valFeat.tsv --feat_out valFeat_sel.tsv --filter_var="age" --allowed_range="[0,120]"
    - Rscript 03_check_for_confounders.r --metadata_in valMetaData_sel.tsv --feat_in valFeat.tsv --plot metaCheck.pdf --label_in valLabel_sel.tsv
    - Rscript 04_filter_features.r --feat_in valFeat_sel.tsv --feat_out valFeat_sel_filtered.tsv --method="abundance" --cutoff="0.001" --rm_unmapped="TRUE"
    - Rscript 05_check_associations.r --feat_in valFeat_sel_filtered.tsv --label_in valLabel_sel.tsv --plot assoc.pdf --col_scheme="RdYlBu" --alpha="0.7" --min_fc="0" --mult_test="fdr" --max_show="50" --detect_limit="1e-06" --plot_type="bean"
    - Rscript 06_normalize_features.r --feat_in valFeat_sel_filtered.tsv --feat_out valFeat_sel_norm.tsv --param_out param_out.tsv --method="log.unit" --log_n0="1e-08" --sd_min_quantile="0.2" --vector_norm="2" --norm_margin="1"
    - Rscript 07_add_metadata_as_predictor.r --feat_in valFeat_sel_norm.tsv --feat_out valFeat_sel_norm.tsv --metadata_in valMetaData_sel.tsv --pred_names="fobt" --std_meta="TRUE"
    - Rscript 08_split_features.r --label_in valLabel_sel.tsv --feat_in valFeat_sel_norm.tsv --data_split dataSplit.Rdata --num_folds="10" --resample="5" --stratify="TRUE" --inseparable="NULL" --metadata_in valMetaData_sel.tsv
  artifacts:
    paths:
      - Rscript_flavor/*
    expire_in: 30 min

  only:
    - master
    - dev

train_model:
  stage: train_model
  before_script:
    - cd Rscript_flavor
    - R CMD INSTALL SIAMCAT_1.0.1.tar.gz
  script:
    - Rscript 09_train_models.r --feat_in valFeat_sel_norm.tsv --label_in valLabel_sel.tsv --method="lasso" --data_split dataSplit.Rdata --mlr_models_list models.RData --stratify="TRUE" --sel_criterion="auprc" --min_nonzero_coeff="2"

  artifacts:
    paths:
      - Rscript_flavor/*
    expire_in: 30 min

  only:
    - master
    - dev

make_predictions:
  stage: make_predictions
  before_script:
    - cd Rscript_flavor
    - R CMD INSTALL SIAMCAT_1.0.1.tar.gz
  script:
    - Rscript 10_make_predictions.r --label_in valLabel_sel.tsv --feat_in valFeat_sel_norm.tsv --data_split dataSplit.Rdata --pred pred.tsv --mlr_models_list models.RData

  artifacts:
    paths:
      - Rscript_flavor/*
    expire_in: 30 min

  only:
    - master
    - dev

evaluate_interpret:
  stage: evaluate_interpret
  before_script:
    - cd Rscript_flavor
    - R CMD INSTALL SIAMCAT_1.0.1.tar.gz
  script:
    - Rscript 11_evaluate_predictions.r --feat_in valFeat_sel_norm.tsv --label_in valLabel_sel.tsv --data_split dataSplit.Rdata --plot evalPlot.pdf --pred pred.tsv
    - Rscript 12_interpret_model.r --label_in valLabel_sel.tsv --feat_in valFeat_sel_norm.tsv --origin_feat valFeat_sel.tsv --metadata_in valMetaData_sel.tsv --mlr_models_list models.RData --plot interpretation.pdf --pred pred.tsv --col_scheme="BrBG" --heatmap_type="zscore" --consens_thres="0.5"

  artifacts:
    paths:
      - Rscript_flavor/*
    expire_in: 30 min

  only:
    - master
    - dev
